# Generated by Django 4.1.2 on 2022-11-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
