# Generated by Django 4.1.2 on 2022-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pictures',
            new_name='picture_1',
        ),
        migrations.AddField(
            model_name='post',
            name='picture_2',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_3',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_4',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_5',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
    ]
