# Generated by Django 4.1.2 on 2023-01-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_post_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
    ]
