# Generated by Django 4.1.2 on 2023-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinfo',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
