# Generated by Django 4.1.2 on 2023-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_information', '0002_addinfo_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinfo',
            name='template_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
