# Generated by Django 4.1.2 on 2023-01-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_information', '0003_addinfo_template_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddInfo',
        ),
    ]
