# Generated by Django 4.1.2 on 2023-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_spec_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
