# Generated by Django 4.1.2 on 2023-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0002_image_image_spec_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
