# Generated by Django 4.1.2 on 2023-01-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='doc',
            new_name='file',
        ),
    ]
